module.exports = {
    /**
     * This list details information about the Dominion Cards that are then used as part of the DominionCardHelp Intent.
     */
    "CARDS_EN_GB" : {
 		"cellar": "Card Type:  Action; Card Cost:  $2; Card Rules:  +1 Action, Discard any number of cards. +1 Card per card discarded.",
		"chapel": "Card Type:  Action; Card Cost:  $2; Card Rules:  Trash up to 4 cards from your hand.",
		"moat": "Card Type:  Action - Reaction; Card Cost:  $2; Card Rules:  +2 Cards, When another player plays an Attack card, you may reveal this from your hand. If you do, you are unaffected by that Attack.",
		"chancellor": "Card Type:  Action; Card Cost:  $3; Card Rules:  +2 Coins, You may immediately put your deck into your discard pile.",
		"village": "Card Type:  Action; Card Cost:  $3; Card Rules:  +1 Card, +2 Actions.",
		"woodcutter": "Card Type:  Action; Card Cost:  $3; Card Rules:  +1 Buy, +2 Coins.",
		"workshop": "Card Type:  Action; Card Cost:  $3; Card Rules:  Gain a card costing up to 4 Coins.",
		"bureaucrat": "Card Type:  Action - Attack; Card Cost:  $4; Card Rules:  Gain a silver card; put it on top of your deck. Each other player reveals a Victory card from his hand and puts it on his deck (or reveals a hand with no Victory cards).",
		"feast": "Card Type:  Action; Card Cost:  $4; Card Rules:  Trash this card. Gain a card costing up to 5 Coins.",
		"gardens": "Card Type:  Victory; Card Cost:  $4; Card Rules:  Variable, Worth 1 Victory for every 10 cards in your deck (rounded down).",
		"militia": "Card Type:  Action - Attack; Card Cost:  $4; Card Rules:  +2 Coins, Each other player discards down to 3 cards in his hand.",
		"moneylender": "Card Type:  Action; Card Cost:  $4; Card Rules:  Trash a Copper from your hand. If you do, +3 Coins.",
		"remodel": "Card Type:  Action; Card Cost:  $4; Card Rules:  Trash a card from your hand. Gain a card costing up to 2 Coins more than the trashed card.",
		"smithy": "Card Type:  Action; Card Cost:  $4; Card Rules:  +3 Cards.",
		"spy": "Card Type:  Action - Attack; Card Cost:  $4; Card Rules:  +1 Card +1 Action Each player (including you) reveals the top card of his deck and either discards it or puts it back, your choice.",
		"thief": "Card Type:  Action - Attack; Card Cost:  $4; Card Rules:  Each other player reveals the top 2 cards of his deck. If they revealed any Treasure cards, they trash one of them that you choose. You may gain any or all of these trashed cards. They discard the other revealed cards.",
		"throne room": "Card Type:  Action; Card Cost:  $4; Card Rules:  Choose an Action card in your hand. Play it twice.",
		"council room": "Card Type:  Action; Card Cost:  $5; Card Rules:  +4 Cards, +1 Buy, Each other player draws a card.",
		"festival": "Card Type:  Action; Card Cost:  $5; Card Rules:  +2 Actions, +1 Buy, +2 Coins.",
		"laboratory": "Card Type:  Action; Card Cost:  $5; Card Rules:  +2 Cards, +1 Action.",
		"library": "Card Type:  Action; Card Cost:  $5; Card Rules:  Draw until you have 7 cards in hand. You may set aside any Action cards drawn this way, as you draw them; discard the set aside cards after you finish drawing.",
		"market": "Card Type:  Action; Card Cost:  $5; Card Rules:  +1 Card, +1 Action, +1 Buy, +1 Coin.",
		"mine": "Card Type:  Action; Card Cost:  $5; Card Rules:  Trash a Treasure card from your hand. Gain a Treasure card costing up to 3 Coins more; put it into your hand.",
		"witch": "Card Type:  Action - Attack; Card Cost:  $5; Card Rules:  +2 Cards, Each other player gains a Curse card.",
		"adventurer": "Card Type:  Action; Card Cost:  $6; Card Rules:  Reveal cards from your deck until you reveal 2 Treasure cards. Put those Treasure cards into your hand and discard the other revealed cards.",
		"courtyard": "Card Type: Action Card Cost: $2 Card Rules: +3 Card, Put a card from your hand on top of your deck.",
		"pawn": "Card Type: Action Card Cost: $2 Card Rules: Choose two: +1 Card, +1 Action, +1 Buy, +1 Coin. (The choices must be different.).",
		"secret chamber": "Card Type: Action - Reaction Card Cost: $2 Card Rules: Discard any number of cards. +1 Coin per card discarded. - When another player plays an Attack card, you may reveal this from your hand. If you do, +2 cards, then put 2 cards from your hand on top of your deck.",
		"great hall": "Card Type: Action - Victory Card Cost: $3 Card Rules: 1 Victory, +1 Card, +1 Action.",
		"masquerade": "Card Type: Action Card Cost: $3 Card Rules: +2 Cards Each player passes a card from his hand to the left at once. Then you may trash a card from your hand.",
		"shanty town": "Card Type: Action Card Cost: $3 Card Rules: +2 Actions, Reveal your hand. If you have no Action cards in hand, +2 Cards.",
		"steward": "Card Type: Action Card Cost: $3 Card Rules: Choose one: +2 Cards; or +2 Coins; or trash 2 cards from your hand.",
		"swindler": "Card Type: Action - Attack Card Cost: $3 Card Rules: +2 Coins, Each other player trashes the top card of his deck and gains a card with the same cost that you choose.",
		"wishing well": "Card Type: Action Card Cost: $3 Card Rules: +1 Card, +1 Action, Name a card, then reveal the top card of your deck. If it is the named card, put it in your hand.",
		"baron": "Card Type: Action Card Cost: $4 Card Rules: +1 Buy, You may discard an Estate card. If you do, +4 Coins. Otherwise, gain an Estate card.",
		"bridge": "Card Type: Action Card Cost: $4 Card Rules: +1 Buy, +1 Coin. All cards (including cards in players' hands) cost 1 Coin less this turn, but not less than 0 Coins.",
		"conspirator": "Card Type: Action Card Cost: $4 Card Rules: +2 Coins. If you've played 3 or more Actions this turn (counting this): +1 Card, +1 Action.",
		"coppersmith": "Card Type: Action Card Cost: $4 Card Rules: Copper produces an extra 1 Coin this turn.",
		"ironworks": "Card Type: Action Card Cost: $4 Card Rules: Gain a card costing up to 4 Coins. If it is an... Action card, +1 Action. Treasure card, +1 Coin. Victory card, +1 Card.",
		"mining village": "Card Type: Action Card Cost: $4 Card Rules: +1 Card, +2 Actions. You may trash this card immediately. If you do, +2 Coins.",
		"scout": "Card Type: Action Card Cost: $4 Card Rules: +1 Action. Reveal the top 4 cards of your deck. Put the revealed Victory cards into your hand. Put the other cards on top of your deck in any order.",
		"duke": "Card Type: Victory Card Cost: $5 Card Rules: Worth 1 Victory per Duchy you have.",
		"minion": "Card Type: Action - Attack Card Cost: $5 Card Rules: +1 Action, Choose one: +2 Coins; or discard your hand, +4 Cards, and each other player with at least 5 cards in hand discards his hand and draws 4 cards.",
		"saboteur": "Card Type: Action - Attack Card Cost: $5 Card Rules: Each other player reveals cards from the top of his deck until revealing one costing 3 Coins or more. He trashes that card and may gain a card costing at most 2 Coins less than it. He discards the other revealed cards.",
		"torturer": "Card Type: Action - Attack Card Cost: $5 Card Rules: +3 Card, Each other player chooses one: he discards 2 cards; or he gains a Curse card, putting it in his hand.",
		"trading post": "Card Type: Action Card Cost: $5 Card Rules: Trash 2 cards from your hand. If you do, gain a silver card; put it into your hand.",
		"tribute": "Card Type: Action Card Cost: $5 Card Rules: The player to your left reveals then discards the top 2 cards of his deck. For each differently named card revealed, if it is an... Action Card, +2 Actions; Treasure Card, +2 Coins; Victory Card, +2 Cards.",
		"upgrade": "Card Type: Action Card Cost: $5 Card Rules: +1 Card, +1 Action, Trash a card from your hand. Gain a card costing exactly 1 Coin more than it.",
		"harem": "Card Type: Treasure - Victory Card Cost: $6 Card Rules: 2 Coins, 2 Victory.",
		"nobles": "Card Type: Action - Victory Card Cost: $6 Card Rules: 2 Victory, Choose one: +3 Cards, or +2 Actions.",
		"embargo": "Card Type: Action Card Cost: $2 Card Rules: +2 Coins, Trash this card. Put an Embargo token on top of a Supply pile. - When a player buys a card, he gains a Curse card per Embargo token on that pile.",
		"haven": "Card Type: Action - Duration Card Cost: $2 Card Rules: +1 Card, +1 Action, Set aside a card from your hand face down. At the start of your next turn, put it into your hand.",
		"lighthouse": "Card Type: Action - Duration Card Cost: $2 Card Rules: +1 Action, Now and at the start of your next turn: +1 Coin. - While this is in play, when another player plays an Attack card, it doesn't affect you.",
		"native village": "Card Type: Action Card Cost: $2 Card Rules: +2 Actions, Choose one: Set aside the top card of your deck face down on your Native Village mat; or put all the cards from your mat into your hand.  You may look at the cards on your mat at any time; return them to your deck at the end of the game.",
		"pearl diver": "Card Type: Action Card Cost: $2 Card Rules: +1 Card, +1 Action, Look at the bottom card of your deck. You may put it on top.",
		"ambassador": "Card Type: Action - Attack Card Cost: $3 Card Rules: Reveal a card from your hand. Return up to 2 copies of it from your hand to the Supply. Then each other player gains a copy of it.",
		"fishing village": "Card Type: Action - Duration Card Cost: $3 Card Rules: +2 Actions, +1 Coin, At the start of your next turn: +1 Action, +1 Coin.",
		"lookout": "Card Type: Action Card Cost: $3 Card Rules: +1 Action, Look at the top 3 cards of your deck. Trash one of them. Discard one of them. Put the other one on top of your deck.",
		"smugglers": "Card Type: Action Card Cost: $3 Card Rules: Gain a copy of a card costing up to 6 Coins that the player to your right gained on his last turn.",
		"warehouse": "Card Type: Action Card Cost: $3 Card Rules: +3 Card, +1 Action, Discard 3 cards.",
		"caravan": "Card Type: Action - Duration Card Cost: $4 Card Rules: +1 Card, +1 Action At the start of your next turn, +1 Card.",
		"cutpurse": "Card Type: Action - Attack Card Cost: $4 Card Rules: +2 Coins, Each other player discards a Copper card (or reveals a hand with no Copper).",
		"island": "Card Type: Action - Victory Card Cost: $4 Card Rules: Set aside this and another card from your hand. Return them to your deck at the end of the game. 2 VP",
		"navigator": "Card Type: Action Card Cost: $4 Card Rules: +2 Coins, Look at the top 5 cards of your deck. Either discard all of them, or put them back on top of your deck in any order.",
		"pirate ship": "Card Type: Action - Attack Card Cost: $4 Card Rules: Choose one: Each other player reveals the top 2 cards of his deck, trashes a revealed Treasure that you choose, discards the rest, and if anyone trashed a Treasure you take a Coin token; or, +1 Coin per Coin token you've taken with Pirate Ships this game.",
		"salvager": "Card Type: Action Card Cost: $4 Card Rules: +1 Buy, Trash a card from your hand. +Coins equal to its cost.",
		"sea hag": "Card Type: Action - Attack Card Cost: $4 Card Rules: Each other player discards the top card of his deck, then gains a Curse card, putting it on top of his deck.",
		"treasure map": "Card Type: Action Card Cost: $4 Card Rules: Trash this and another copy of Treasure Map from your hand. If you do trash two Treasure Maps, gain 4 Gold cards, putting them on top of your deck.",
		"bazaar": "Card Type: Action Card Cost: $5 Card Rules: +1 Card, +2 Actions, +1 Coin.",
		"explorer": "Card Type: Action Card Cost: $5 Card Rules: You may reveal a Province card from your hand. If you do, gain a Gold card, putting it into your hand. Otherwise, gain a Silver card, putting it into your hand.",
		"ghost ship": "Card Type: Action - Attack Card Cost: $5 Card Rules: +2 Card, Each other player with 4 or more cards in hand puts cards from his hand on top of his deck until he has 3 cards in his hand.",
		"merchant ship": "Card Type: Action - Duration Card Cost: $5 Card Rules: Now and at the start of your next turn: +2 Coins.",
		"outpost": "Card Type: Action - Duration Card Cost: $5 Card Rules: You only draw 3 cards (instead of 5) in this turn's Clean-up phase. Take an extra turn after this one. This can't cause you to take more than two consecutive turns.",
		"tactician": "Card Type: Action - Duration Card Cost: $5 Card Rules: Discard your hand. If you discarded any cards this way, then at the start of your next turn, +5 Cards, +1 Buy, and +1 Action.",
		"treasury": "Card Type: Action Card Cost: $5 Card Rules: +1 Card, +1 Action, +1 Coin, When you discard this from play, if you didn't buy a Victory card this turn, you may put this on top of your deck.",
		"wharf": "Card Type: Action - Duration Card Cost: $5 Card Rules: Now and at the start of your next turn: +2 Cards, +1 Buy.",
		"harbinger": "Card Type: Action Card Cost: $3 Card Rules: +1 Card, +1 Action Look through your discard pile. You may put a card from it onto your deck.",
		"merchant": "Card Type: Action Card Cost: $3 Card Rules: +1 Card +1 Action The first tim eyou play a Silver this turn, +1 Coin.",
		"vassal": "Card Type: Action Card Cost: $3 Card Rules: +2 Coins Discard the top card of your deck. If it's an Action card, you may play it.",
		"poacher": "Card Type: Action Card Cost: $4 Card Rules: +1 Card +1 Action +1 Coin Discard a card per empty Supply pile.",
		"bandit": "Card Type: Action - Attack Card Cost: $5 Card Rules: Gain a Gold. Each other player reveals the top 2 cards of their deck, trashes a revealed Treasure other than Copper, and discards the rest.",
		"sentry": "Card Type: Action Card Cost: $5 Card Rules: +1 Card +1 Action Look at the top 2 cards of your deck. Trash and/or discard any number of them. Put the rest back on top in any order.",
		"artisan": "Card Type: Action Card Cost: $6 Card Rules: Gain a card to your hand costing up to 5 Coins. Put a card from yoru hand onto your deck."		
	}
 };
