module.exports = {
    /**
     * This list details information about the Dominion Cards that are then used as part of the DominionCardHelp Intent.
     */
    "BASE" : {
 		1:"Cellar",
		2:"Chapel",
		3:"Moat",
		4:"Village",
		5:"Woodcutter",
		6:"Workshop",
		7:"Bureaucrat",
		8:"Feast",
		9:"Gardens",
		10:"Militia",
		11:"Moneylender",
		12:"Remodel",
		13:"Smithy",
		14:"Spy",
		15:"Thief",
		16:"Throne Room",
		17:"Council Room",
		18:"Festival",
		19:"Laboratory",
		20:"Library",
		21:"Market",
		22:"Mine",
		23:"Witch",
		24:"Adventurer"
    },
	"BASE2" : {
 		1:"Cellar",
		2:"Chapel",
		3:"Moat",
		4:"Village",
		5:"Woodcutter",
		6:"Workshop",
		7:"Bureaucrat",
		8:"Feast",
		9:"Gardens",
		10:"Militia",
		11:"Moneylender",
		12:"Remodel",
		13:"Smithy",
		14:"Spy",
		15:"Thief",
		16:"Throne Room",
		17:"Council Room",
		18:"Festival",
		19:"Laboratory",
		20:"Library",
		21:"Market",
		22:"Mine",
		23:"Witch",
		24:"Adventurer",
		25:"Artisan",
		26:"Bandit",
		27:"Harbinger",
		28:"Merchant",
		29:"Poacher",
		30:"Sentry",
		31:"Vassal"
    },
	"SEASIDE" : {
		1:"Embargo",
		2:"Haven",
		3:"Lighthouse",
		4:"Native Village",
		5:"Pearl Diver",
		6:"Ambassador",
		7:"Fishing Village",
		8:"Lookout",
		9:"Smugglers",
		10:"Warehouse",
		11:"Caravan",
		12:"Cutpurse",
		13:"Island",
		14:"Navigator",
		15:"Pirate Ship",
		16:"Salvager",
		17:"Sea Hag",
		18:"Treasure Map",
		19:"Bazaar",
		20:"Explorer",
		21:"Ghost Ship",
		22:"Merchant Ship",
		23:"Outpost",
		24:"Tactician",
		25:"Treasury",
		26:"Wharf"
    },
	"INTRIGUE" : {
		1:"Courtyard",
		2:"Pawn",
		3:"Secret Chamber",
		4:"Great Hall",
		5:"Masquerade",
		6:"Shanty Town",
		7:"Steward",
		8:"Swindler",
		9:"Wishing Well",
		10:"Baron",
		11:"Bridge",
		12:"Conspirator",
		13:"Coppersmith",
		14:"Ironworks",
		15:"Mining Village",
		16:"Scout",
		17:"Duke",
		18:"Minion",
		19:"Saboteur",
		20:"Torturer",
		21:"Trading Post",
		22:"Tribute",
		23:"Upgrade",
		24:"Harem",
		25:"Nobles"
    }
 };
